"""add color and icon to role

Revision ID: 0770c87882b0
Revises: d49ae13fb12b
Create Date: 2026-06-04 14:55:33.133482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0770c87882b0'
down_revision = 'd49ae13fb12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
