"""config: add toast_duration column

Revision ID: 1f3f6d62dc9c
Revises: 9e0989e7ad39
Create Date: 2026-06-03 10:25:51.312536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3f6d62dc9c'
down_revision = '9e0989e7ad39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toast_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.drop_column('toast_duration')

    # ### end Alembic commands ###
