"""add protected to role

Revision ID: 27667c17de6a
Revises: 0770c87882b0
Create Date: 2026-06-04 14:59:23.882803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27667c17de6a'
down_revision = '0770c87882b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('protected')

    # ### end Alembic commands ###
