"""add_tag_table

Revision ID: 44977930303a
Revises: d240e91167fb
Create Date: 2026-06-12 15:05:06.362036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44977930303a'
down_revision = 'd240e91167fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tag_namespace'), ['namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_source'))
        batch_op.drop_index(batch_op.f('ix_tag_namespace'))
        batch_op.drop_index(batch_op.f('ix_tag_name'))
        batch_op.drop_index(batch_op.f('ix_tag_is_public'))
        batch_op.drop_index(batch_op.f('ix_tag_created_by'))

    op.drop_table('tag')
    # ### end Alembic commands ###
