"""rule content rename cve cleanup add history

Revision ID: 538254aca866
Revises: 8e210bc97155
Create Date: 2026-06-17 10:50:45.689131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538254aca866'
down_revision = '8e210bc97155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('previous_content', sa.Text(), nullable=True),
    sa.Column('previous_version', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('change_summary', sa.String(length=512), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['rule_edit_proposal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_history_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_history_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_history_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_history_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_history_version_num'), ['version_num'], unique=False)

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('cve_id')
        batch_op.drop_column('to_string')

    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('previous_version', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        batch_op.drop_column('previous_version')
        batch_op.drop_column('previous_content')

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_string', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('cve_id', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('content')

    with op.batch_alter_table('rule_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_history_version_num'))
        batch_op.drop_index(batch_op.f('ix_rule_history_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_history_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_rule_history_changed_by'))
        batch_op.drop_index(batch_op.f('ix_rule_history_changed_at'))
        batch_op.drop_index(batch_op.f('ix_rule_history_change_type'))

    op.drop_table('rule_history')
    # ### end Alembic commands ###
