"""add format_rule table link rule format_id

Revision ID: 64b4886ae08f
Revises: 538254aca866
Create Date: 2026-06-17 10:52:47.413985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b4886ae08f'
down_revision = '538254aca866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('format_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_extension', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('can_be_executed', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('format_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_format_rule_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_format_rule_name'), ['name'], unique=True)

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rule_format'))
        batch_op.create_index(batch_op.f('ix_rule_format_id'), ['format_id'], unique=False)
        batch_op.create_foreign_key(None, 'format_rule', ['format_id'], ['id'])
        batch_op.drop_column('format')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rule_format_id'))
        batch_op.create_index(batch_op.f('ix_rule_format'), ['format'], unique=False)
        batch_op.drop_column('format_id')

    with op.batch_alter_table('format_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_format_rule_name'))
        batch_op.drop_index(batch_op.f('ix_format_rule_created_at'))

    op.drop_table('format_rule')
    # ### end Alembic commands ###
