"""add verification fields to user

Revision ID: 78f415858cc0
Revises: 27667c17de6a
Create Date: 2026-06-05 09:15:43.581932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f415858cc0'
down_revision = '27667c17de6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('verification_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_expires_at')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
