"""add rule tables

Revision ID: 8e210bc97155
Revises: 6f364d327281
Create Date: 2026-06-17 10:47:33.131298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e210bc97155'
down_revision = '6f364d327281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('original_uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('to_string', sa.Text(), nullable=True),
    sa.Column('rule_hash', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('mitre_attack', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('false_positives', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('github_path', sa.String(length=512), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cve_id', sa.String(length=512), nullable=True),
    sa.Column('vote_up', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('remote_rule_uuid', sa.String(length=36), nullable=True),
    sa.Column('sync_instance_url', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('delete_batch_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_delete_batch_uuid'), ['delete_batch_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_original_uuid'), ['original_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_remote_rule_uuid'), ['remote_rule_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_rule_hash'), ['rule_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_uuid'), ['uuid'], unique=True)

    op.create_table('rule_cve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'cve_id', name='uq_rule_cve')
    )
    with op.batch_alter_table('rule_cve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_cve_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_cve_rule_id'), ['rule_id'], unique=False)

    op.create_table('rule_edit_proposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('proposed_content', sa.Text(), nullable=True),
    sa.Column('proposed_description', sa.Text(), nullable=True),
    sa.Column('diff_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_edit_proposal_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_edit_proposal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_edit_proposal_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_edit_proposal_user_id'), ['user_id'], unique=False)

    op.create_table('rule_favorite_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'user_id', name='uq_rule_favorite')
    )
    with op.batch_alter_table('rule_favorite_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_favorite_user_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_favorite_user_user_id'), ['user_id'], unique=False)

    op.create_table('rule_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'tag_id', name='uq_rule_tag')
    )
    with op.batch_alter_table('rule_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_tag_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_tag_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_tag_tag_id'))
        batch_op.drop_index(batch_op.f('ix_rule_tag_rule_id'))

    op.drop_table('rule_tag')
    with op.batch_alter_table('rule_favorite_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_favorite_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_rule_favorite_user_rule_id'))

    op.drop_table('rule_favorite_user')
    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_edit_proposal_user_id'))
        batch_op.drop_index(batch_op.f('ix_rule_edit_proposal_timestamp'))
        batch_op.drop_index(batch_op.f('ix_rule_edit_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_rule_edit_proposal_rule_id'))

    op.drop_table('rule_edit_proposal')
    with op.batch_alter_table('rule_cve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_cve_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_cve_cve_id'))

    op.drop_table('rule_cve')
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_user_id'))
        batch_op.drop_index(batch_op.f('ix_rule_title'))
        batch_op.drop_index(batch_op.f('ix_rule_status'))
        batch_op.drop_index(batch_op.f('ix_rule_severity'))
        batch_op.drop_index(batch_op.f('ix_rule_rule_hash'))
        batch_op.drop_index(batch_op.f('ix_rule_remote_rule_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_original_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_last_modif'))
        batch_op.drop_index(batch_op.f('ix_rule_is_verified'))
        batch_op.drop_index(batch_op.f('ix_rule_is_public'))
        batch_op.drop_index(batch_op.f('ix_rule_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_rule_format'))
        batch_op.drop_index(batch_op.f('ix_rule_delete_batch_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_creation_date'))
        batch_op.drop_index(batch_op.f('ix_rule_created_at'))
        batch_op.drop_index(batch_op.f('ix_rule_connector_id'))

    op.drop_table('rule')
    # ### end Alembic commands ###
