"""config: add toast_position and toast_style columns

Revision ID: 9e0989e7ad39
Revises: 7272ba35aa94
Create Date: 2026-06-03 10:19:32.460159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0989e7ad39'
down_revision = '7272ba35aa94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toast_position', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('toast_style', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.drop_column('toast_style')
        batch_op.drop_column('toast_position')

    # ### end Alembic commands ###
