"""user: add force_logout column

Revision ID: acf68e051c38
Revises: b1dd6b274f4f
Create Date: 2026-06-03 13:37:57.791638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf68e051c38'
down_revision = 'b1dd6b274f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_logout', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_logout')

    # ### end Alembic commands ###
