"""user: add is_verified, session_version, last_seen_at

Revision ID: b1dd6b274f4f
Revises: 1f3f6d62dc9c
Create Date: 2026-06-03 13:31:13.191318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dd6b274f4f'
down_revision = '1f3f6d62dc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))

    # Backfill created_at NULLs with current timestamp
    op.execute("UPDATE \"user\" SET created_at = datetime('now') WHERE created_at IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('session_version')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
