"""add pending email change fields to user

Revision ID: bc8dad771541
Revises: 78f415858cc0
Create Date: 2026-06-05 09:47:48.213608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8dad771541'
down_revision = '78f415858cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pending_email_token', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('pending_email_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pending_email_expires_at')
        batch_op.drop_column('pending_email_token')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
