"""account: extend user profile fields

Revision ID: e6e62528f3a7
Revises: eed2e8b869cb
Create Date: 2026-06-03 09:46:09.570333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e62528f3a7'
down_revision = 'eed2e8b869cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('social_twitter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('social_github', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('social_linkedin', sa.String(length=200), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('social_linkedin')
        batch_op.drop_column('social_github')
        batch_op.drop_column('social_twitter')
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('company')
        batch_op.drop_column('job_title')
        batch_op.drop_column('phone')
        batch_op.drop_column('avatar_filename')
        batch_op.drop_column('bio')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
