"""add log table

Revision ID: f6e9e0798847
Revises: 078d1576ed4b
Create Date: 2026-06-03 13:59:00.589877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e9e0798847'
down_revision = '078d1576ed4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_level'), ['level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_level'))
        batch_op.drop_index(batch_op.f('ix_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_log_category'))
        batch_op.drop_index(batch_op.f('ix_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_log_action'))

    op.drop_table('log')
    # ### end Alembic commands ###
